server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://user-db:3306/user_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

internal:
  secret: ${INTERNAL_SECRET}

logging:
  level:
    com.founderlink.user: DEBUG
